"""
Example: Saving FeatCopilot Features to Feast Feature Store

This example demonstrates how to:
1. Generate features with FeatCopilot
2. Save them to Feast for reuse and serving
3. Retrieve features for training and inference

Prerequisites:
    pip install featcopilot[feast]

Note: This example uses a local Feast setup with SQLite.
For production, configure Feast with your preferred backend.
"""

from datetime import datetime, timedelta

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

from featcopilot import AutoFeatureEngineer
from featcopilot.stores import FeastFeatureStore


def create_sample_data(n_samples: int = 1000) -> pd.DataFrame:
    """Create sample customer data for churn prediction."""
    np.random.seed(42)

    data = pd.DataFrame(
        {
            # Entity column (unique identifier)
            "customer_id": range(1, n_samples + 1),
            # Event timestamp
            "event_timestamp": [datetime.now() - timedelta(days=np.random.randint(0, 30)) for _ in range(n_samples)],
            # Features
            "age": np.random.randint(18, 80, n_samples),
            "tenure_months": np.random.randint(1, 120, n_samples),
            "monthly_charges": np.random.uniform(20, 150, n_samples),
            "total_charges": np.random.uniform(100, 10000, n_samples),
            "num_support_tickets": np.random.poisson(2, n_samples),
            "contract_type": np.random.choice(["month-to-month", "one_year", "two_year"], n_samples),
        }
    )

    # Create target (churn) based on features
    churn_prob = (
        0.3
        - 0.002 * data["tenure_months"]
        + 0.003 * data["monthly_charges"]
        + 0.05 * data["num_support_tickets"]
        + 0.2 * (data["contract_type"] == "month-to-month").astype(int)
    )
    churn_prob = np.clip(churn_prob, 0.05, 0.95)
    data["churned"] = (np.random.random(n_samples) < churn_prob).astype(int)

    return data


def main():
    print("=" * 70)
    print("FeatCopilot + Feast Feature Store Example")
    print("=" * 70)

    # =========================================================================
    # Step 1: Create sample data
    # =========================================================================
    print("\n1. Creating sample customer data...")
    data = create_sample_data(1000)
    print(f"   - Samples: {len(data)}")
    print(f"   - Columns: {list(data.columns)}")

    # Separate features and target
    feature_cols = ["age", "tenure_months", "monthly_charges", "total_charges", "num_support_tickets"]
    X = data[["customer_id", "event_timestamp"] + feature_cols].copy()
    y = data["churned"]

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # =========================================================================
    # Step 2: Generate features with FeatCopilot
    # =========================================================================
    print("\n2. Generating features with FeatCopilot...")

    # Keep entity columns separate for feature engineering
    X_train_features = X_train[feature_cols].copy()
    X_test_features = X_test[feature_cols].copy()

    engineer = AutoFeatureEngineer(
        engines=["tabular"],
        max_features=30,
        verbose=True,
    )

    X_train_fe = engineer.fit_transform(X_train_features, y_train)
    X_test_fe = engineer.transform(X_test_features)

    print(f"   - Original features: {len(feature_cols)}")
    print(f"   - Generated features: {len(X_train_fe.columns)}")

    # Add back entity columns and timestamp
    X_train_fe["customer_id"] = X_train["customer_id"].values
    X_train_fe["event_timestamp"] = X_train["event_timestamp"].values

    X_test_fe["customer_id"] = X_test["customer_id"].values
    X_test_fe["event_timestamp"] = X_test["event_timestamp"].values

    # =========================================================================
    # Step 3: Save features to Feast
    # =========================================================================
    print("\n3. Saving features to Feast feature store...")

    # Initialize Feast store
    store = FeastFeatureStore(
        repo_path="./feast_feature_repo",
        project_name="churn_prediction",
        entity_columns=["customer_id"],
        timestamp_column="event_timestamp",
        ttl_days=365,
        auto_materialize=True,  # Sync to online store
    )

    # Initialize and save features
    store.initialize()

    store.save_features(
        df=X_train_fe,
        feature_view_name="customer_churn_features",
        description="Customer features for churn prediction, generated by FeatCopilot",
    )

    print("   - Saved to feature view: 'customer_churn_features'")
    print("   - Feature store path: ./feast_feature_repo")

    # =========================================================================
    # Step 4: List and inspect feature views
    # =========================================================================
    print("\n4. Inspecting feature store...")

    feature_views = store.list_feature_views()
    print(f"   - Available feature views: {feature_views}")

    schema = store.get_feature_view_schema("customer_churn_features")
    print(f"   - Schema: {len(schema.get('features', []))} features")
    for feat in schema.get("features", [])[:5]:
        print(f"     - {feat['name']}: {feat['dtype']}")
    if len(schema.get("features", [])) > 5:
        print(f"     - ... and {len(schema['features']) - 5} more")

    # =========================================================================
    # Step 5: Retrieve features for training (offline)
    # =========================================================================
    print("\n5. Retrieving features from offline store (for training)...")

    # Create entity DataFrame for retrieval
    entity_df = pd.DataFrame(
        {
            "customer_id": X_test["customer_id"].values,
            "event_timestamp": X_test["event_timestamp"].values,
        }
    )

    # Get feature names (exclude entity and timestamp)
    feature_names = [c for c in X_train_fe.columns if c not in ["customer_id", "event_timestamp"]]

    retrieved_features = store.get_features(
        entity_df=entity_df,
        feature_names=feature_names[:10],  # Get first 10 features
        feature_view_name="customer_churn_features",
        online=False,
    )

    print(f"   - Retrieved {len(retrieved_features.columns)} columns for {len(retrieved_features)} entities")

    # =========================================================================
    # Step 6: Get features from online store (for inference)
    # =========================================================================
    print("\n6. Getting features from online store (for real-time inference)...")

    # Simulate real-time inference for a few customers
    inference_customers = {"customer_id": [1, 2, 3]}

    online_features = store.get_online_features(
        entity_dict=inference_customers,
        feature_names=feature_names[:5],  # Get first 5 features
        feature_view_name="customer_churn_features",
    )

    print(f"   - Retrieved online features for customers: {inference_customers['customer_id']}")
    for key, values in list(online_features.items())[:3]:
        print(f"     - {key}: {values}")

    # =========================================================================
    # Step 7: Train model using features
    # =========================================================================
    print("\n7. Training model with generated features...")

    # Prepare training data (using locally transformed features)
    train_feature_cols = [c for c in X_train_fe.columns if c not in ["customer_id", "event_timestamp"]]
    X_train_final = X_train_fe[train_feature_cols].fillna(0)
    X_test_final = X_test_fe[train_feature_cols].fillna(0)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train_final, y_train)

    y_pred = model.predict(X_test_final)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"   - Model accuracy: {accuracy:.4f}")

    # =========================================================================
    # Cleanup
    # =========================================================================
    print("\n8. Cleanup...")
    store.close()
    print("   - Feature store connection closed")

    print("\n" + "=" * 70)
    print("Example completed!")
    print("=" * 70)
    print("\nKey takeaways:")
    print("  - FeatCopilot generates features automatically")
    print("  - Feast stores features for reuse and serving")
    print("  - Offline store: historical features for training")
    print("  - Online store: real-time features for inference")
    print("\nFeature repo saved at: ./feast_feature_repo")


if __name__ == "__main__":
    main()
